# fly.toml app configuration file generated for jquery-server-side-calculator on 2023-09-12T09:44:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jquery-server-side-calculator"
primary_region = "ord"

[env]
  PORT = "8080"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
